### ISSUE TITLE
copying the commands to bash

### ISSUE THREAD

**Issue by ido1990** [KD4Z/md380tools-vm#11]
Hi!
I tried to install it on Debian (VM) and this step:
**cp md380tools-vm/root/.bash_aliases ~**
Didn't work for me.
The correct filename on Debian was **.bashrc** instead of **.bash_aliases**
73!

**Comment by KD4Z** [comment]
I believe you may have overwritten code in your .bashrc that you need.  .bashrc calls out to .bash_aliases  You didn't need to overwrite .bashrc.  What exactly didn't work?  You realize that you have to logout and log back in to get bash to run the newly created .bash_aliases right?

**Comment by ido1990** [comment]
I've used an image of debian, didn't install fresh copy so maybe that caused the issue.
I fixed it already by changing the name and all the commands works well.

**Comment by KD4Z** [comment]
I don't yet understand what issue you had.   If I understand your solution correctly, you deleted .bashrc and renamed .bash_aliases to .bashrc   Again, you likely lost other user specific setup and environment variables that are configured in a normal .bashrc.   You should create another user on your system, and study what the default script is in that new user's .bashrc   You will see it calls out to .bash_aliases.   You can of course, paste in the content of .bash_aliases at the bottom of .bashrc, but that defeats the purpose of having the aliases managed in a separate file.

**Comment by ido1990** [comment]
Just wanted to point it out, maybe others will encounter this issue.
I checked the original .bashrc file before I renamed it, all the lines are commented out.

**Comment by KD4Z** [comment]
Normally the .bashrc has  a lot of script that isn't commented out.  Since the call out to .bash_aliases must have been commented out too, the alias file didn't run.   Your setup isn't default and doesn't represent what a typical user would experience.    Glad it is working, though if I were you, I'd go back and study what is in the normal .bashrc and redo the setup.  You can create another user and play around with it, without breaking your current working setup.
