### ISSUE TITLE
download contacts

### ISSUE THREAD

**Issue by fcoffey** [KD4Z/md380tools-vm#2]
Do not know if this is an issue u can answer but when I do the flashdb it clears the memory and says it is writing but after complete it is not there. It did not flash anything that I can find anywhere.

**Comment by KD4Z** [comment]
Hi.   Make sure you enable the UsersCSV option in the MD380tools menu.  The contacts will not show up if that option is not enabled.   You might have missed it in the PDF.  It's on page 7.

**Comment by PD1LOI** [comment]
Here the same fault
If I ~ / lookup 2047075 to give exakt I see my data as we want it. but it does not load in my postage. if I flashdb ingeef, the port in USB mode. when the charge is complete reboot nothing the postage too, but it is in. I put UserCVS in MD380Tools than I see only the ID number which is also normal to me. I put it on I see ID unknown
no entry in your user.csv Strange huh?

**Comment by fcoffey** [comment]
Enable csv in tools

**Comment by PD1LOI** [comment]
I have to be, but whatever I do, there is nothing written in my MD-380.
"Flash" is performed correctly.

**Comment by fcoffey** [comment]
There is 3 steps to the upgrade the last is db to format and install the csv database.

**Comment by KD4Z** [comment]
Loui, take a look at the pdf directions again.  See page 7 for enable UsersCSV  There is a page for recipes also.    All have flashdb as the last step.  As you run flashdb, do you see any errors on the screen?  Like "Device not found"  or "Device has 1M flash, can not update"    If you see this, you have an older radio that doesn't have the 16Meg flash chip, and so you can't use the UserCSV mode.     Also,  make sure you have updated to the 3.0 version.  When you glv, it will update to the current version of 3.03

**Comment by PD1LOI** [comment]
I know, I do always load the user.csv by travis. Normal linux hole through it just as well. Only through the VM user.csv do not want my MD-380. Here, according to Travis command in Linux, http://www.randstadamateur.net/index.php/tytera-md-380md-390-hacks/md380-tools/
and it just works.
I have no errors when I VM "flash" or "flashdb" input.

**Comment by KD4Z** [comment]
Press the Green Menu button.  Press Up arrow to get to Utilities.  Go to option #4 MD380Tools.   Select option #4 there for UsersCSV.   Press Up and down arrows to show which option has the dark blue dot.  If you see it on the top option for Enable, you have it selected.  If not, move selection bar to the Enable line, and Press the Green menu button to Confirm.  The display should say "UserCSV enable"  It is easy to make mistake in this screen.  It can look enabled, when it is not.

**Comment by PD1LOI** [comment]
Green button Menu Utilities MD380Tools, users.CVS = ON Enable is dark.
I had already mentioned but the DB is not written to the MD380, but erased.
Firmware will be written to the MD380.
And that is the problem here, even when I use another PC.
It seems that when the data should be written on the radio read only state.

**Comment by PD1LOI** [comment]
VirtualBox COM Server 5.1.12 r112440 win.x86 (Dec 20 2016 16:01:00) release log
00:00:00.015604 main     Log opened 2017-01-09T17:12:32.101579000Z
00:00:00.015604 main     Build Type: release
00:00:00.015604 main     OS Product: Windows 10
00:00:00.015604 main     OS Release: 10.0.14393
00:00:00.015604 main     OS Service Pack: 
00:00:00.069294 main     DMI Product Name:                                 
00:00:00.084917 main     DMI Product Version: F.0A
00:00:00.084917 main     Host RAM: 3063MB (2.9GB) total, 2055MB (2.0GB) available
00:00:00.084917 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.084917 main     Process ID: 3420
00:00:00.084917 main     Package type: WINDOWS_32BITS_GENERIC
00:00:00.084917          VirtualBox: object creation starts
00:00:00.084917          Home directory: 'C:\Users\l_kup\.VirtualBox'
00:00:00.084917          Installed Drivers:
00:00:00.188286            C:\Windows\system32\DRIVERS\VBoxNetAdp6.sys (Version: 5.1.12.12440)
00:00:00.252300            C:\Windows\system32\DRIVERS\VBoxNetLwf.sys (Version: 5.1.12.12440)
00:00:00.351580            C:\Windows\system32\DRIVERS\VBoxUSBMon.sys (Version: 5.1.12.12440)
00:00:00.584404            C:\Windows\system32\DRIVERS\VBoxDrv.sys (Version: 5.1.12.12440)
00:00:00.631275          Loading settings file "C:\Users\l_kup\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.821467          usbLibDevCfgDrGet: DeviceIoControl 1 fail dwErr (31)
00:00:01.026573          HostDnsMonitor: old information
00:00:01.026573            no server entries
00:00:01.026573            no domain set
00:00:01.026573            no search string entries
00:00:01.026573          HostDnsMonitor: new information
00:00:01.026573            server 1: 192.168.2.254
00:00:01.026573            server 2: 213.75.63.75
00:00:01.026573            server 3: 213.75.63.76
00:00:01.026573            domain: home
00:00:01.026573            no search string entries
00:00:01.026573          HostDnsMonitorProxy::notify
00:00:01.131349          SUPR0QueryVTCaps -> VERR_VMX_MSR_ALL_VMX_DISABLED
00:00:01.383825          VD: VDInit finished
00:00:01.483864          VirtualBox: object created
00:02:05.759408          Import settings with version "1.14-windows"
00:02:05.759408          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={0169423f-46b4-cde9-91af-1e9d5b6cd945} aComponent={VirtualBoxWrap} aText={Could not find a registered machine named 'tyt'}, preserve=false aResultDetail=0
00:02:05.759408          ERROR [COM]: aRC=VBOX_E_FILE_ERROR (0x80bb0004) aIID={4afe423b-43e0-e9d0-82e8-ceb307940dda} aComponent={MediumWrap} aText={Could not find file for the medium 'C:\Users\l_kup\VirtualBox VMs\tyt\tyt_3.0-disk1.vmdk' (VERR_PATH_NOT_FOUND)}, preserve=false aResultDetail=0
00:03:28.954451          ERROR [COM]: aRC=E_FAIL (0x80004005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={MachineWrap} aText={This machine does not have any snapshots}, preserve=false aResultDetail=0
00:04:40.154468          Load [C:\Program Files\Oracle\VirtualBox\ExtensionPacks\Oracle_VM_VirtualBox_Extension_Pack\win.x86\VBoxHostWebcam.DLL] rc VINF_SUCCESS
00:04:41.189996          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={SessionMachine} aText={Saved screenshot data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:08:55.788067          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={SessionMachine} aText={Saved screenshot data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:10:41.080741          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={SessionMachine} aText={Saved screenshot data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:10:51.490789          ERROR [COM]: aRC=E_INVALIDARG (0x80070057) aIID={c19073dd-cc7b-431b-98b2-951fda8eab89} aComponent={HostUSBDeviceWrap} aText={USB device 'STMicroelectronics STM Device in DFU Mode' with UUID {efea48bd-4add-4591-a1a1-25fa9ab2b8f7} is busy with a previous request. Please try again later}, preserve=true  aResultDetail=0
00:11:16.319239          ERROR [COM]: aRC=E_INVALIDARG (0x80070057) aIID={c19073dd-cc7b-431b-98b2-951fda8eab89} aComponent={HostUSBDeviceWrap} aText={USB device 'STMicroelectronics STM Device in DFU Mode' with UUID {efea48bd-4add-4591-a1a1-25fa9ab2b8f7} is busy (state 'CapturingForVM[Attach]'). Please try again later}, preserve=false aResultDetail=0
00:11:16.469019          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={MachineWrap} aText={Saved screenshot thumbnail data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:11:16.496357          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={b2547866-a0a1-4391-8b86-6952d82efaa0} aComponent={MachineWrap} aText={Saved screenshot thumbnail data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=0
00:11:23.853394 main     VirtualBox: object deletion starts
00:11:23.853394 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={4afe423b-43e0-e9d0-82e8-ceb307940dda} aComponent={MediumWrap} aText={Medium 'C:\Users\l_kup\VirtualBox VMs\tyt\tyt_3.0-disk1.vmdk' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:11:23.853394 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={0169423f-46b4-cde9-91af-1e9d5b6cd945} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:11:23.853394 main     VirtualBox: object deleted

**Comment by KD4Z** [comment]
Without any comment on what you are getting to have this log,  it looks like you have corrupted the VM somehow.  I would just delete the tyt VM from VirtualBox Manager, and reimport the OVA appliance file again.

**Comment by PD1LOI** [comment]
![virtualbox_tyt_09_01_2017_23_24_13](https://cloud.githubusercontent.com/assets/2943825/21786346/b286cbdc-d6c3-11e6-8756-b92b08e14175.png)

Everything seems to work, but no db is written to the MD-380.

**Comment by PD1LOI** [comment]
After the update this morning (GLV) is all ok also db is now loaded.
Thanks KD4Z
73 PD1LOI

**Comment by KD4Z** [comment]
Excellent.   Time to enjoy!.   Closing this ticket now.
