### ISSUE TITLE
Display - Last line - Missing text

### ISSUE THREAD

**Issue by pjao** [KD4Z/md380tools-vm#23]
Here it goes two examples.

It should be Portugal. This are the lines of user.bin

Hope it can help.

![imagem](https://user-images.githubusercontent.com/6640329/35475651-fe521216-0399-11e8-9416-e7de4279d5cc.png)

![2018-01-27 19 36 38](https://user-images.githubusercontent.com/6640329/35475626-a6ef4430-0399-11e8-9c3b-97bbb5d6749f.jpg)
![2018-01-27 19 36 56](https://user-images.githubusercontent.com/6640329/35475627-a8020fba-0399-11e8-96c4-60329cbc8818.jpg)

**Comment by pjao** [comment]
![p_20180127_200818](https://user-images.githubusercontent.com/6640329/35475885-25c15ba0-039e-11e8-9860-c8bad1bc3dc2.jpg)
It looks like that area could not have text.

**Comment by KD4Z** [comment]
Correct. There is some artifact of the OEM firmware that clears that area.  I have removed the space after the comma separator in an attempt to get one more character on the line.   Otherwise, I will have to reduce the character max by one and a lot more entries will end up showing in the smaller font.  glv again @pjao   Portugal should actually fit for Porto now.

**Comment by pjao** [comment]
Fixed, Thanks.

But could be a good idea, see text size, and if it is >13 then reduce the font size

**Comment by KD4Z** [comment]
![7](https://user-images.githubusercontent.com/17788589/35483396-80bb0d50-040f-11e8-9a90-b45de7e785e0.png)   I've added logic to display city in small font if it won't fit in the large font.

**Comment by pjao** [comment]
It looks nice in city. You could have it on state,country.

Let's wait for the PR.

**Comment by KD4Z** [comment]
You are going to wait a long time.  I already had it on state and country from last week so nothing more to do.
