### ISSUE TITLE
MD-380 old vocoder no display

### ISSUE THREAD

**Issue by dbaker1611** [KD4Z/md380tools-vm#8]
With the latest experimental firmware I lose the display on the MD-380. It stays on for a moment during turn-on then goes off. Not able to see to access settings to deal with display. re-loading MFG firmware corrects issue but when re-loading experimental firmware same issue. At the moment you can either chose "flash" or "flashgps", any chance on a "flash" for the old vocoder? 

The "flash" worked under 3.08 but not working now under 3.09.

Thank you!

**Comment by dbaker1611** [comment]
Found this is already being discussed here:
https://github.com/travisgoodspeed/md380tools/issues/687

**Comment by KD4Z** [comment]
Yes, I was going to recommend going to the Google group on this.  I was
thinking that you might be able to just drive through the keystrokes into
the back light settings and get a different value saved.  I suspect it's a
boundary condition not tested.  You would need someone to read off the
exact steps to get there since you can'take see the screen!

On Feb 14, 2017 5:00 PM, "dbaker1611" <notifications@github.com> wrote:

Found this is already being discussed here:
travisgoodspeed/md380tools#687
<https://github.com/travisgoodspeed/md380tools/issues/687>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KD4Z/md380tools-vm/issues/8#issuecomment-279849790>,
or mute
the thread

**Comment by dbaker1611** [comment]
found a work-a-round on one of the other areas where having your codeplug or manually setting Backlight to 5s or anything else other than Always under Radio Settings on main utilities seems to work. Radio seems to be working now under the experimental firmware but not able to have Backlight always on now.

**Comment by KD4Z** [comment]
Ok, I've forwarded this on to others who seem to be having the same
issues.  Thanks for letting me know what you found out!

73 de KD4Z
Warren
